= Automatic updates

It might be usefull to have some upgrades done completely automatically if it doesn't prevent the server from working properly and
even enhance its security.

NOTE:  See https://ubuntu.com/server/docs/package-management in the sub-section "Automatic Updates"

== Installation and setup

[source, bash]
----
#1st) Install unattended-upgrades
sudo apt install unattended-upgrades

#2nd) Check '/etc/apt/apt.conf.d/50unattended-upgrades' 
# - It seems digitalocean basic configuration is pretty sensible already 
#
// Automatically upgrade packages from these (origin:archive) pairs
//
// Note that in Ubuntu security updates may pull in new dependencies
// from non-security sources (e.g. chromium). By allowing the release
// pocket these get automatically pulled in.
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        // Extended Security Maintenance; doesn't necessarily exist for
        // every release and this system may not have it installed, but if
        // available, the policy for updates is such that unattended-upgrades
        // should also install from here by default.
        "${distro_id}ESMApps:${distro_codename}-apps-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
//      "${distro_id}:${distro_codename}-updates";
//      "${distro_id}:${distro_codename}-proposed";
//      "${distro_id}:${distro_codename}-backports";
};

#3rd) Tell Ubuntu to autoupgrade and how in  '/etc/apt/apt.conf.d/20auto-upgrades'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
----

**from the OA** 
*The above configuration updates the package list, downloads, and installs available upgrades every day. The local download archive is cleaned every week. On servers upgraded to newer versions of Ubuntu, depending on your responses, the file listed above may not be there. In this case, creating a new file of this name should also work.*

== Notifications trough email

=== via /etc/apt/apt.conf.d/50unattended-upgrades
[code, bash]
----
// Send email to this address for problems or packages upgrades
// If empty or unset then no email is sent, make sure that you
// have a working mail setup on your system. A package that provides
// 'mailx' must be installed. E.g. "user@example.com"
Unattended-Upgrade::Mail "myName.mySurname+Unattended-Upgrade.enigma.digitalocean@gmail.com";
----

=== apticron

I'll install it too, I 'll see wether I get flooded by emails. Maybe it's usefull for other purposes

[code, bash]
----
#Install apticron
sudo apt install apticron

#Edit '/etc/apticron/apticron.conf'
EMAIL="myName.mySurname+Unattended-Upgrade.enigma.digitalocean@gmail.com"
----
